try {
    test();//eta wrong,cz i didn't use "function"
}
catch(e) {
    console.log(e);
}